<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DeadlineDiscoveryServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DeadlineDiscoveryServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DeadlineDiscoveryServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://deadlineDiscovery.g15.ws/">
    <import location="http://localhost:8080/DeadlineDiscovery/DeadlineDiscoveryService?wsdl" namespace="http://deadlineDiscovery.g15.ws/"/>
    <plnk:partnerLinkType name="DeadlineFinderLinkType">
        <plnk:role name="DeadlineFinderRole" portType="ns:DeadlineFinder"/>
    </plnk:partnerLinkType>
</definitions>
